---
##########################
## Hadolint config file ##
##########################
ignored:
	- DL3018 # Pin versions in apk add - See: https://github.com/hadolint/hadolint/wiki/DL3018
	- DL3013 # Pin versions in pip - See: https://github.com/hadolint/hadolint/wiki/DL3013
